refactor!: rename marketplace to appstore
defenseunicorns/uds-appstore pull request #287
Opened 2024-10-04 04:43 UTC by andrewg-xyz

2024-10-04 05:18 UTC, jonnyborbs requested changes
At a meta-level we should align on whether we are calling this `appstore` or `uds-AppStore`. I know we decided to shorten away from `airgap-app-store` for brevity and ease of use of the code, but we should align clearly on whether this is actually the UDS App Store, or if it’s the Airgap App Store (shortened to appstore), then make sure this PR is consistent with that decision throughout

2024-10-04 05:18 UTC, jonnyborbs commented on .air.toml
> +  bin = "./build/appstore"
these are `/appstore` but many other places are `/uds-appstore`, should we ensure they’re consistent throughout?

2024-10-04 05:18 UTC, jonnyborbs commented on .github/ISSUE_TEMPLATE/epic.md
> +about: Add a vertical slice of functionality to UDS App Store
```suggestion
name: New Epic for Airgap App Store
about: Add a vertical slice of functionality to Airgap App Store
```

2024-10-04 05:18 UTC, jonnyborbs commented on dockerfile
Another series of `/appstore` vs `/uds-appstore` inconsistencies we should check out

2024-10-04 05:18 UTC, jonnyborbs commented on ui/src/lib/features/navigation/navbar/navbar.svelte
> +					<img src="/doug.svg" alt="uds appstore logo" />
```suggestion
					<img src="/doug.svg" alt="airgap appstore logo" />
```

2024-10-07 16:14 UTC, andrewg-xyz commented on .air.toml
> +  bin = "./build/appstore"
updated

2024-10-07 16:14 UTC, andrewg-xyz commented on dockerfile
updated

2024-10-07 17:39 UTC, jonnyborbs requested changes
two really minor nits remain otherwise great job tidying up the consistency!

2024-10-07 17:39 UTC, jonnyborbs commented on developer.md
> +To create a k3d cluster and deploy a slim version of UDS with metrics server and appstore:
nit : should this be styled as App Store?

```suggestion
To create a k3d cluster and deploy a slim version of UDS with metrics server and App Store:
```

2024-10-07 17:39 UTC, jonnyborbs commented on tasks/release.yaml
> +    description: "Build the Airgap App Store and publish a release. NOTE: task isn't intended to be ran local"
```suggestion
    description: "Build the Airgap App Store and publish a release. NOTE: task isn't intended to be run local"
```

2024-10-07 17:41 UTC, jonnyborbs commented on developer.md
> +To create a k3d cluster and deploy a slim version of UDS with metrics server and appstore:
this MAY not be a desirable change if you're referring to "appstore the image" not "appstore the product" but if that was the case, I'd expect `metrics-server` etc, so I think we are talking products here

2024-10-07 18:09 UTC, merged