feat(ui): UDS FAQ page
defenseunicorns/uds-appstore pull request #322
Opened 2024-10-15 23:23 UTC by andrewrisse

2024-10-16 15:24 UTC, andrewg-xyz approved these changes

2024-10-16 17:44 UTC, gregclark-defenseunicorns requested changes
- Add "While" to 2nd FAQ question to read as "While UDS applications are pre-integrated, the platform..."

- Add stylized link to "DoD DevSecOps Reference Design" in the 4th FAQ question. Navigate to https://dodcio.defense.gov/Portals/0/Documents/DoD%20Enterprise%20DevSecOps%20Reference%20Design%20v1.0_Public%20Release.pdf

- Move "We accelerate not only your initial ATO but also ensure continuous deployment by automating security validations as part of the delivery process." to a separate line with a blank line above it like it is in the Google Doc.
![Screenshot 2024-10-16 at 11 14 18 AM](https://github.com/user-attachments/assets/e52f84e6-9d55-4643-88f4-0e2e18032c94)

- Move "Our services  provide  continuous monitoring, technical support, vulnerability management, and education, including:" to a separate to a separate line with a blank line above it like it is in the Google Doc. Also, add a blank line above "Speak to one of our Mission experts about..." to match Google Doc.
![Screenshot 2024-10-16 at 11 40 03 AM](https://github.com/user-attachments/assets/257e80c5-a7fe-497f-84d8-d2d4e08478ea)

2024-10-17 13:23 UTC, andrewrisse commented
> * Add "While" to 2nd FAQ question to read as "While UDS applications are pre-integrated, the platform..."
> * Add stylized link to "DoD DevSecOps Reference Design" in the 4th FAQ question. Navigate to https://dodcio.defense.gov/Portals/0/Documents/DoD%20Enterprise%20DevSecOps%20Reference%20Design%20v1.0_Public%20Release.pdf
> * Move "We accelerate not only your initial ATO but also ensure continuous deployment by automating security validations as part of the delivery process." to a separate line with a blank line above it like it is in the Google Doc.
>   ![Screenshot 2024-10-16 at 11 14 18 AM](https://private-user-images.githubusercontent.com/123974425/377161351-e52f84e6-9d55-4643-88f4-0e2e18032c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzEyOTYsIm5iZiI6MTcyOTE3MDk5NiwicGF0aCI6Ii8xMjM5NzQ0MjUvMzc3MTYxMzUxLWU1MmY4NGU2LTlkNTUtNDY0My04OGY0LTBlMmUxODAzMmM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxMzE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTJhNzNiM2Q4NTRmNjlhOTc5MGIwNmQxMzNmMWQwMmVmOTI5ZjdjOTUxNDU0NDQ5YWRiODZjNjVmMDEzYzE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kOMibd59xKPu99xrUgJIBn0CSYAVOpgU2LM2lNOx3vk)
> * Move "Our services  provide  continuous monitoring, technical support, vulnerability management, and education, including:" to a separate to a separate line with a blank line above it like it is in the Google Doc. Also, add a blank line above "Speak to one of our Mission experts about..." to match Google Doc.
>   ![Screenshot 2024-10-16 at 11 40 03 AM](https://private-user-images.githubusercontent.com/123974425/377169263-257e80c5-a7fe-497f-84d8-d2d4e08478ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzEyOTYsIm5iZiI6MTcyOTE3MDk5NiwicGF0aCI6Ii8xMjM5NzQ0MjUvMzc3MTY5MjYzLTI1N2U4MGM1LWE3ZmUtNDk3Zi04NGQ4LWQyZDRlMDg0NzhlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxMzE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjNlYWZjMWIxODIyZjk2MzdlMzhkOWM4NTQyYzAyMWY4YmU5MDNkODRkOWE2OTQ4MzZkNTBjYmViZDlhYjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fjHdcjv7TTxvENPqJd0n_v2ydyHOsikroDZw_MwwLwM)

completed

2024-10-17 14:26 UTC, andrewg-xyz requested changes
would like to sync before merging

2024-10-17 18:31 UTC, closed without merging